from typing import Dict, List, Any
from .models import Workflow, Node, Edge
from .nodes import NodeRegistry


class WorkflowExporter:
    def __init__(self, workflow: Workflow):
        self.workflow = workflow

    def export(self) -> str:
        lines = []
        
        lines.append("#!/usr/bin/env python3")
        lines.append("# -*- coding: utf-8 -*-")
        lines.append("")
        lines.append(f"# Workflow: {self.workflow.name}")
        lines.append(f"# Generated by Low-Code Platform")
        lines.append("")
        
        lines.append("import math")
        lines.append("import json")
        lines.append("")
        lines.append("# ========================================")
        lines.append("# Workflow Execution")
        lines.append("# ========================================")
        lines.append("")
        
        execution_order = self._get_execution_order()
        
        lines.append("def run_workflow():")
        lines.append('    """Execute the workflow and return the result."""')
        lines.append("")
        lines.append("    # Context to store node outputs")
        lines.append("    context = {}")
        lines.append("    node_outputs = {}")
        lines.append("")
        
        for node_model in execution_order:
            node = NodeRegistry.create_node(node_model)
            if node is None:
                continue
            
            node_var = f"node_{node_model.id.replace('-', '_')}"
            lines.append(f"    # Node: {node_model.type} ({node_model.label or node_model.id})")
            
            inputs_code = self._generate_inputs_code(node_model, execution_order)
            lines.append(f"    {node_var}_inputs = {inputs_code}")
            
            if node_model.type == "start":
                params = node_model.config.params
                lines.append(f"    {node_var}_inputs = {repr(params)}")
                lines.append(f"    node_outputs['{node_model.id}'] = {{'params': {node_var}_inputs}}")
            elif node_model.type == "end":
                lines.append(f"    # End node collects final result")
                lines.append(f"    context['__final_result__'] = {node_var}_inputs.get('result')")
            elif node_model.type == "python_code":
                code = node_model.config.code
                lines.append("")
                lines.append("    # User code")
                lines.append("    result = None")
                for line in code.split('\n'):
                    lines.append(f"    {line}")
                lines.append("")
                lines.append(f"    node_outputs['{node_model.id}'] = {{'result': result}}")
            elif node_model.type == "condition":
                expr = node_model.config.params.get("expression", "True")
                true_val = node_model.config.params.get("true_value")
                false_val = node_model.config.params.get("false_value")
                lines.append(f"    # Condition evaluation")
                lines.append(f"    _condition = bool({expr})")
                lines.append(f"    node_outputs['{node_model.id}'] = {{")
                lines.append(f"        'condition': _condition,")
                lines.append(f"        'true': {repr(true_val)} if _condition else None,")
                lines.append(f"        'false': {repr(false_val)} if not _condition else None")
                lines.append(f"    }}")
            
            lines.append("")
        
        lines.append("    return context.get('__final_result__')")
        lines.append("")
        
        lines.append("")
        lines.append("if __name__ == \"__main__\":")
        lines.append("    result = run_workflow()")
        lines.append('    print("Workflow execution completed.")')
        lines.append('    print("Result:", result)')
        
        return "\n".join(lines)

    def _get_execution_order(self) -> List[Node]:
        nodes = self.workflow.nodes
        edges = self.workflow.edges
        
        if not edges:
            return nodes
        
        node_map = {node.id: node for node in nodes}
        
        in_degree = {node.id: 0 for node in nodes}
        adjacency = {node.id: [] for node in nodes}
        
        for edge in edges:
            source = edge.source
            target = edge.target
            if source in adjacency and target in in_degree:
                adjacency[source].append(target)
                in_degree[target] += 1
        
        from collections import deque
        queue = deque()
        for node_id, degree in in_degree.items():
            if degree == 0:
                queue.append(node_id)
        
        execution_order = []
        
        while queue:
            node_id = queue.popleft()
            execution_order.append(node_id)
            
            for neighbor in adjacency[node_id]:
                in_degree[neighbor] -= 1
                if in_degree[neighbor] == 0:
                    queue.append(neighbor)
        
        result = []
        for node_id in execution_order:
            if node_id in node_map:
                result.append(node_map[node_id])
        
        return result

    def _generate_inputs_code(self, node_model: Node, execution_order: List[Node]) -> str:
        incoming_edges = [
            e for e in self.workflow.edges if e.target == node_model.id
        ]
        
        if not incoming_edges:
            return "{}"
        
        inputs_dict = {}
        for edge in incoming_edges:
            source_id = edge.source
            inputs_dict[f"from_{source_id.replace('-', '_')}"] = f"node_outputs.get('{source_id}', {{}})"
        
        if len(inputs_dict) == 1:
            return list(inputs_dict.values())[0]
        
        return "{" + ", ".join([f"'{k}': {v}" for k, v in inputs_dict.items()]) + "}"
