"""initial migration

Revision ID: 76f3e3b640d4
Revises: 
Create Date: 2026-04-24 11:54:22.025242

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76f3e3b640d4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('permissions', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_role_name'), ['name'], unique=True)

    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    op.create_table('user_group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_group', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_group_name'), ['name'], unique=True)

    op.create_table('survey',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('access_password', sa.String(length=128), nullable=True),
    sa.Column('max_responses', sa.Integer(), nullable=True),
    sa.Column('require_login', sa.Boolean(), nullable=True),
    sa.Column('require_captcha', sa.Boolean(), nullable=True),
    sa.Column('limit_per_ip', sa.Integer(), nullable=True),
    sa.Column('limit_per_cookie', sa.Boolean(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('survey', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_survey_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_survey_creator_id'), ['creator_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_survey_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_survey_status'), ['status'], unique=False)

    op.create_table('user_group_member',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['user_group.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'group_id')
    )
    op.create_table('user_role',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    op.create_table('question',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('survey_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('options', sa.JSON(), nullable=True),
    sa.Column('is_required', sa.Boolean(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('logic_jump', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['survey_id'], ['survey.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('survey_id', 'order', name='uq_survey_question_order')
    )
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_question_order'), ['order'], unique=False)
        batch_op.create_index(batch_op.f('ix_question_survey_id'), ['survey_id'], unique=False)

    op.create_table('response',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('survey_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('is_valid', sa.Boolean(), nullable=True),
    sa.Column('invalid_reason', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['survey_id'], ['survey.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('response', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_response_ip_address'), ['ip_address'], unique=False)
        batch_op.create_index(batch_op.f('ix_response_submitted_at'), ['submitted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_response_survey_id'), ['survey_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_response_user_id'), ['user_id'], unique=False)

    op.create_table('response_answer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('response_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['response_id'], ['response.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('response_id', 'question_id', name='uq_response_question')
    )
    with op.batch_alter_table('response_answer', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_response_answer_question_id'), ['question_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_response_answer_response_id'), ['response_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('response_answer', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_response_answer_response_id'))
        batch_op.drop_index(batch_op.f('ix_response_answer_question_id'))

    op.drop_table('response_answer')
    with op.batch_alter_table('response', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_response_user_id'))
        batch_op.drop_index(batch_op.f('ix_response_survey_id'))
        batch_op.drop_index(batch_op.f('ix_response_submitted_at'))
        batch_op.drop_index(batch_op.f('ix_response_ip_address'))

    op.drop_table('response')
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_question_survey_id'))
        batch_op.drop_index(batch_op.f('ix_question_order'))

    op.drop_table('question')
    op.drop_table('user_role')
    op.drop_table('user_group_member')
    with op.batch_alter_table('survey', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_survey_status'))
        batch_op.drop_index(batch_op.f('ix_survey_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_survey_creator_id'))
        batch_op.drop_index(batch_op.f('ix_survey_created_at'))

    op.drop_table('survey')
    with op.batch_alter_table('user_group', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_group_name'))

    op.drop_table('user_group')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_role_name'))

    op.drop_table('role')
    # ### end Alembic commands ###
